### PR TITLE
Tidy up some dependencies and tests

### PR DESCRIPTION
**Pull request by ljedrz**
No functional changes, just quality of life / developer experience ones plus a small dependency update.

As always, the commits describe the specific changes.

### CODE REVIEW

**Review by aphelionz — APPROVED** [review]
very nice

bors r+

**Comment by ljedrz** [comment]
`tests::kademlia::dht_providing` seems to have failed when running in `go-ipfs` interop mode; can't reproduce locally and those tests are still pretty fresh, so perhaps it's a random glitch?
bors retry

**Comment by ljedrz** [comment]
I will have my way :smiley:
bors retry

**Comment by ljedrz** [comment]
oh, so cancelling jobs doesn't cancel bors?
bors r-

**Pull request merged**
