### PR TITLE
chore(clippy)

### PR DESCRIPTION
**Pull request by Mirko-von-Leipzig**
Changes with clippy fixes. Split into smaller commits -- can be squashed if desired.

### CODE REVIEW

**Comment by Mirko-von-Leipzig** [comment]
> 
> 
> @Mirko-von-Leipzig could you rebase this on top of the latest master? Also please ~drop~ revert commit [0196134](https://github.com/rs-ipfs/rust-ipfs/commit/019613425d14164c077419bca90d8483571adbae) where I allowed clippy and rustfmt to fail.

Done

**Review by koivunej — APPROVED** [review]
Thanks, looking good!

**Comment by koivunej** [comment]
Allowing you to `bors r+` in case it fails again, but it looked transient -- like the windows boxes were being busy.

bors d+

**Pull request merged**
