### PR TITLE
update libp2p again

### PR DESCRIPTION
**Pull request by ljedrz**
Needed for our `substrate-ipfs` project, as `substrate` just updated it.

### CODE REVIEW

**Comment by ljedrz** [comment]
This should be libp2p/rust-libp2p@5291175, as this it when the tag was released.

**Comment by ljedrz** [comment]
afterwards we might want to retry our noise attempts; Cc https://github.com/rs-ipfs/rust-ipfs/issues/175

**Comment by koivunej** [comment]
Yes advancing #175 that should now be possible

**Comment by ljedrz** [comment]
`exchange_block` timed out again; we'll retry once #254 is merged.

**Pull request merged**
