### PR TITLE
Return time since connection if no round trip yet

### LINKED ISSUE #178: No latency in verbose swarm/peers before a ping response
Test log: https://github.com/rs-ipfs/rust-ipfs/pull/177/checks?check_run_id=749321323#step:9:192

I am not sure what the other implementations could possibly be doing here. Counting up from the connection established would be the correct way to go about this.

_Originally posted by @koivunej in https://github.com/rs-ipfs/rust-ipfs/pull/177#issuecomment-640487950_

### PR DESCRIPTION
**Pull request by jmmaloney4**
Fixes #178.

### CODE REVIEW

**Comment by koivunej** [comment]
I gave this a quick look and it seems great, thanks for doing this! I was thinking that maybe the one of the existing hashmaps could perhaps be used for this but ... That would then complicate other things. The connection tracking parts are a bit overdue for proper cleanup and moving upwards to rust-libp2p.

There's now some npm related breakage but the build failing at that step means that the (few) rust tests passed. Oki, it's most likely because I have forgotten an old url there. I'll probably handle this on a separate PR.

Could you take care of the rustfmt issue? Just do a `cargo fmt` and commit.

**Comment by jmmaloney4** [comment]
Oops

**Comment by mxinden** [comment]
> The connection tracking parts are a bit overdue for proper cleanup and moving upwards to rust-libp2p.

Happy to discuss tracking the time of a connection in rust-libp2p. Feel free to open an issue on https://github.com/libp2p/rust-libp2p/.

**Comment by koivunej** [comment]
Thanks for this @jmmaloney4. I have to admit I forgot about this PR while hustling the #480, apologies for that.

I've rebased this on top of the latest master. The second commit was not needed anymore so it was dropped, and I simplified with the use of [`Instant::elapsed`](https://doc.rust-lang.org/stable/std/time/struct.Instant.html#method.elapsed). I also edited the PR description to remove the checklist which does not really apply here, and it will be copied by bors to the merge commit.

It looks like conformance tests agree, so I'll push a changelog entry and merge this. Thanks again.

**Comment by koivunej** [comment]
@mxinden 
> Happy to discuss tracking the time of a connection in rust-libp2p. Feel free to open an issue on https://github.com/libp2p/rust-libp2p/.

I will try to remember this and apologies on the late reply once more for you as well. I think the big cleanup is overdue with me really understanding the `Merge inject_* paired methods` PR working through these easier changes. Mostly the problems are within the rust-ipfs, trying to write code to support different interleavings of polls vs. injections while providing a futures api.

**Comment by koivunej** [comment]
bors retry

**Comment by koivunej** [comment]
Well, this is ackward.

bors retry

**Comment by koivunej** [comment]
Well, it would appear that gha is having some issues now with the bad credentials issue. I'll try again later.

**Comment by koivunej** [comment]
bors retry

**Pull request merged**
