### PR TITLE
This PR uses libp2p dns, so that /dns4 and /dns6 multiaddrs can be dialed.

### PR DESCRIPTION
**Pull request by rklaehn**
Not quite sure how to best test this without having a test that uses the dns of the CI server. Any ideas?

### CODE REVIEW

**Comment by koivunej** [comment]
Thanks for this! The feature was accidentially dropped off while trimming down the deps in #276.

Yeah proper testing for this is probably quite difficult. I wished there was an action which would spin up a local ... dnsmasq for this? It would probably suffice, but yeah a lot of legwork as I cannot find such right away.

I wonder if the test case could however be a swarm connect on such valid dns multiaddress. I think it should immediatedly respond with unsupported protocol error or whatever it was if the feature was *not included*. This would at least remind us why that feature is enabled :) In the test, every other failure and a small for example 10s timeout could be accepted.

**Comment by koivunej** [comment]
The test failures are transient issues downloading toolchain.

**Comment by rklaehn** [comment]
I tried doing such a test, but it turns out that you do get a timeout in any case. Looks like the failed dial somehow gets lost...

```rust
// Make sure two instances of ipfs can be connected by `Multiaddr`.
#[tokio::test(max_threads = 1)]
async fn dial_dns() {
    let node_a = Node::new("a").await;
    let node_b = Node::new("b").await;
    let (b_publickey, _) = node_b.identity().await.unwrap();
    let b_peer_id = b_publickey.into_peer_id();

    // check dns4
    let addr = libp2p::build_multiaddr!(Dns4(Cow::Borrowed("localhost")), Tcp(0u16), P2p(b_peer_id.clone()));
    let res = timeout(Duration::from_secs(1), node_a.connect(addr)).await;
    assert!(matches!(res, Err(tokio::time::Elapsed { .. })));

    // check dns6
    let addr = libp2p::build_multiaddr!(Dns6(Cow::Borrowed("localhost")), Tcp(0u16), P2p(b_peer_id.clone()));
    let res = timeout(Duration::from_secs(1), node_a.connect(addr)).await;
    assert!(matches!(res, Err(tokio::time::Elapsed { .. })));

    // check dns
    let addr = libp2p::build_multiaddr!(Dns(Cow::Borrowed("localhost")), Tcp(0u16), P2p(b_peer_id.clone()));
    let res = timeout(Duration::from_secs(1), node_a.connect(addr)).await;
    assert!(matches!(res, Err(tokio::time::Elapsed { .. })));

    // check dnsaddr
    let addr = libp2p::build_multiaddr!(Dnsaddr(Cow::Borrowed("localhost")), Tcp(0u16), P2p(b_peer_id));
    let res = timeout(Duration::from_secs(1), node_a.connect(addr)).await;
    assert!(matches!(res, Err(tokio::time::Elapsed { .. })));
}
```

**Comment by koivunej** [comment]
Right of the bat I wouldn't be too surprised if an event doesn't cancel the subscription. Then again, we have spent a lot of time on that part, and probably will spend a lot time in the future :) I am running a bit out of steam with the large pin related work I've been doing lately but I'd init tracing_subscriber in the test, followed by making sure `IpfsFuture` traces all events from the swarm poll and `ipfs::p2p::swarm::SwarmApi` sees the connection failure...

**Comment by koivunej** [comment]
After a few attempts the logs look like for your proposed test:

```
2020-09-04T14:05:25.552289Z TRACE ipfs{node="a"}: libp2p_dns: Dialing address with DNS: /dns4/localhost/tcp/0
2020-09-04T14:05:25.553091Z DEBUG ipfs{node="a"}: libp2p_dns: DNS resolution outcome: /dns4/localhost/tcp/0 => /ip4/127.0.0.1/tcp/0
2020-09-04T14:05:25.553197Z DEBUG ipfs{node="a"}: libp2p_tcp: Instantly refusing dialing /ip4/127.0.0.1/tcp/0, as it is invalid
2020-09-04T14:05:25.553493Z DEBUG ipfs{node="a"}: libp2p_swarm: Connection attempt to address "/dns4/localhost/tcp/0" of unknown peer failed with Transport(Other(Custom { kind: Other, error: Custom { kind: Other, error: Other(A(A(Underlying
(Kind(ConnectionRefused))))) } }))
2020-09-04T14:05:25.553589Z TRACE ipfs{node="a"}: ipfs::p2p::swarm: inject_addr_reach_failure /dns4/localhost/tcp/0 Pending connection: Transport error: connection refused
2020-09-04T14:05:25.553669Z TRACE ipfs{node="a"}: ipfs: UnknownPeerUnreachableAddr { address: "/dns4/localhost/tcp/0", error: Transport(Other(Custom { kind: Other, error: Custom { kind: Other, error: Other(A(A(Underlying(Kind(ConnectionRefu
sed))))) } })) }
2020-09-04T14:05:26.553165Z TRACE ipfs::subscription: Dropping subscription future 0 to Connect to MultiaddrWithPeerId { multiaddr: MultiaddrWithoutPeerId("/dns4/localhost/tcp/0"), peer_id: PeerId("12D3KooWDVpSK9JkrDvJ4jHaiwUHToXZLKuA7BSWVt
QnRJ5NKX4i") }
2020-09-04T14:05:26.553543Z TRACE ipfs::subscription: Cancelling subscription 0 to Connect to MultiaddrWithPeerId { multiaddr: MultiaddrWithoutPeerId("/dns4/localhost/tcp/0"), peer_id: PeerId("12D3KooWDVpSK9JkrDvJ4jHaiwUHToXZLKuA7BSWVtQnRJ5
NKX4i") }
```

I got these by adding `tracing_subscriber::fmt::init()` to the beginning of it, then running with `RUST_LOG=trace,cargo=off cargo test --test dial_dns -- --nocapture` with your test in `tests/dial_dns.rs`.

**Comment by rklaehn** [comment]
The issue is that the peer id is being stripped before dialing, because rust-libp2p only likes to dial addrs w/o peer id. Then you do get a dial failure as expected, but the code in `inject_addr_reach_failure` is unable to figure out for which addr to call finish_subscription...

**Comment by koivunej** [comment]
Tried getting the Tcp port off the `node_b` addresses from `node_b.identity()` and now the test passes. The extraction is not pretty but there could be a better one. So it would seem that the errors were caused by trying to dial to port 0. The test still fails but there are now much lot more logs, did not shift through yet. Just a sec I'll push this.

**Comment by koivunej** [comment]
Pushed, relevant lines: https://github.com/koivunej/rust-ipfs/blob/b0b78a0a5638900e781e0fd5142574a9f94aa856/tests/dial_dns.rs#L15-L41

**Comment by rklaehn** [comment]
Did you check that this does *not* pass when you remove the `DnsConfig(...)?`?

**Comment by koivunej** [comment]
With the dnsconfig commented out:

```
2020-09-04T14:28:12.184236Z TRACE ipfs{node="a"}: ipfs::p2p::swarm: Connecting to MultiaddrWithPeerId { multiaddr: MultiaddrWithoutPeerId("/dns4/localhost/tcp/33031"), peer_id: PeerId("12D3KooWP6zFr7vdeAGB25pmJqY5tS1goTuucD5ZvqgioyYJuhrh")
}
2020-09-04T14:28:12.184382Z DEBUG ipfs{node="a"}: ipfs::subscription: Creating subscription 0 to Connect to MultiaddrWithPeerId { multiaddr: MultiaddrWithoutPeerId("/dns4/localhost/tcp/33031"), peer_id: PeerId("12D3KooWP6zFr7vdeAGB25pmJqY5t
S1goTuucD5ZvqgioyYJuhrh") }
2020-09-04T14:28:12.184588Z DEBUG ipfs{node="a"}: bitswap::behaviour: bitswap: new_handler
2020-09-04T14:28:12.184662Z TRACE ipfs{node="a"}: ipfs::p2p::swarm: new_handler
2020-09-04T14:28:12.185075Z DEBUG ipfs{node="a"}: libp2p_swarm: Connection attempt to address "/dns4/localhost/tcp/33031" of unknown peer failed with Transport(MultiaddrNotSupported("/dns4/localhost/tcp/33031"))
2020-09-04T14:28:12.185168Z TRACE ipfs{node="a"}: ipfs::p2p::swarm: inject_addr_reach_failure /dns4/localhost/tcp/33031 Pending connection: Transport error: Multiaddr is not supported: /dns4/localhost/tcp/33031
2020-09-04T14:28:12.185240Z TRACE ipfs{node="a"}: ipfs: UnknownPeerUnreachableAddr { address: "/dns4/localhost/tcp/33031", error: Transport(MultiaddrNotSupported("/dns4/localhost/tcp/33031")) }
2020-09-04T14:28:13.185631Z TRACE ipfs::subscription: Dropping subscription future 0 to Connect to MultiaddrWithPeerId { multiaddr: MultiaddrWithoutPeerId("/dns4/localhost/tcp/33031"), peer_id: PeerId("12D3KooWP6zFr7vdeAGB25pmJqY5tS1goTuucD
5ZvqgioyYJuhrh") }
2020-09-04T14:28:13.186031Z TRACE ipfs::subscription: Cancelling subscription 0 to Connect to MultiaddrWithPeerId { multiaddr: MultiaddrWithoutPeerId("/dns4/localhost/tcp/33031"), peer_id: PeerId("12D3KooWP6zFr7vdeAGB25pmJqY5tS1goTuucD5Zvqg
ioyYJuhrh") }
2020-09-04T14:28:13.186840Z TRACE ipfs{node="a"}: ipfs::p2p::swarm: Connecting to MultiaddrWithPeerId { multiaddr: MultiaddrWithoutPeerId("/dns6/localhost/tcp/33031"), peer_id: PeerId("12D3KooWP6zFr7vdeAGB25pmJqY5tS1goTuucD5ZvqgioyYJuhrh")
}
```

**Comment by rklaehn** [comment]
So if it passes with DnsConfig... and does not pass without DnsConfig... it is good to go I guess?

**Comment by koivunej** [comment]
I'll need to look at the test more, if I can trigger it to actually fail and not just have the dial fail. However, could very well be that this does not need a test. I'll try to get back to this on monday.

**Review by koivunej — APPROVED** [review]
Thanks @rklaehn 

bors r+

**Pull request merged**
