### PR TITLE
update remaining deps

### PR DESCRIPTION
**Pull request by ljedrz**
In order to tackle the test timeout issue I decided to update the remaining dependencies to make sure the root cause is not already fixed upstream.

The only direct dependency that couldn't be updated is `unsigned-varint`, because `cid` depends on the version we are currently using.

### CODE REVIEW

**Comment by ljedrz** [comment]
A linker error in Windows? I don't think I have't seen those before, I'll retry when all the others are complete.

**Comment by ljedrz** [comment]
A linker error again; it's in `ipfs-http` and points to `openssl`.

**Comment by ljedrz** [comment]
No more `Cargo.lock` changes to `openssl`, but the Windows build still fails at linking `openssl` :shrug:; package caching?

**Comment by koivunej** [comment]
mac failure is #134.

**Comment by koivunej** [comment]
The windows caching is likely the culprit here. Today I learned vcpkg is in fact using submodules for all of the `ports/` so I am now thinking if we could somehow pin that version. Then using that "pin" as a cache key would be the proper course.

**Comment by koivunej** [comment]
This should be rebased on top of the latest master following #267, which resolved the caching issue.

**Comment by ljedrz** [comment]
The mac failure is the fimeout; if Windows passes, this is good to go.

**Comment by ljedrz** [comment]
Yep, all good - it's good to go @koivunej.

**Pull request merged**
