### PR TITLE
bitswap: Update libp2p

### PR DESCRIPTION
**Pull request by matthiasbeyer**
As suggsted in #485 I re-started my efforts starting with the `/bitswap` subtree for updating libp2p.

Supersedes #485 

---

Feel free to suggest how to continue! :laughing:

### CODE REVIEW

**Comment by koivunej** [comment]
Great you've been making progress, thanks also for Max (cannot tag from mobile ui) for helping out. I will be out of office until next week (xmas holidays) when I hope to fix the build and then merge this. Again, thanks for doing this!

Note that I only suggested that you'd start the upgrade from first getting the `bitswap/` work, possibly leaving it implicit that you should continue to upgrade `ipfs` or the root crate after that. The libp2p upgrade should be on a single PR, even though it affects two parts or more parts (`http/`). Also, feel free to rebase your work on the PR as much as you want, just avoiding merges in the PR branch. However if the git-fu becomes an issue, I can take care of that when merging as well.

**Comment by matthiasbeyer** [comment]
> I will be out of office until next week 

Sure, no hurry!

> Note that I only suggested that you'd start the upgrade from first getting the bitswap/ work, possibly leaving it implicit that you should continue to upgrade ipfs or the root crate after that.

Yes, sure! Upgrading bitswap was ... doable, but I fail to see why the root crate does not compile, so I figured I rather push this into a PR and we go from there instead me just becoming desperate :laughing: 

> However if the git-fu becomes an issue, I can take care of that when merging as well.

No worries, I am a git ninja (>10 years experience, with different workflows and even email workflows etc etc)!

**Review by mxinden — APPROVED** [review]
Changes itself look good to me.

**Review by koivunej — APPROVED** [review]
This is looking good; compilation fails on your branch though, so the rest of the upgrade needs to be done on the ipfs side. If libp2p has already advanced to a next major version, then I'd suggest doing the ongoing upgrade first before moving on to the next.

**Comment by koivunej** [comment]
Similar to #485, closing this as libp2p has been upgraded to 0.43.

**Pull request closed without merging**
